version: '3.7'

services:
   db:
     image: king607267/cmangos-classic-db:latest
     ports:
       - "3306:3306"
     volumes:
       - yourpath/db:/var/lib/mysql
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: mangos
       MYSQL_PASSWORD: mangos
       MYSQL_USER: mangos
       TZ: Asia/Shanghai

   realmd:
     depends_on:
       - db
     image: king607267/cmangos-classic-realmd:latest
     ports:
       - "3724:3724"
     restart: "no"
     environment:
       LOGIN_DATABASE_INFO: db;3306;mangos;mangos;classicrealmd
       TZ: Asia/Shanghai

   server:
     tty: true
     stdin_open: true
     depends_on:
       - db
       - realmd
     image: king607267/cmangos-classic-server:latest
     volumes:
       - yourpath/maps:/etc/mangos/maps
       - yourpath/vmaps:/etc/mangos/vmaps
       - yourpath/mmaps:/etc/mangos/mmaps
       - yourpath/dbc:/etc/mangos/dbc
       - yourpath/Cameras:/etc/mangos/Cameras
     ports:
       - "8085:8085"
     restart: "no"
     environment:
       LOGIN_DATABASE_INFO: db;3306;mangos;mangos;classicrealmd
       WORLD_DATABASE_INFO: db;3306;mangos;mangos;classicmangos
       CHARACTER_DATABASE_INFO: db;3306;mangos;mangos;classiccharacters
       TZ: Asia/Shanghai